package chap14_exception;

public class _03_throws {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr = new int[9];
	}
	
	public static void getException(int[] intArr) 
							throws Exception {
		for(int i = 0; i < 10; i++) {
			System.out.println(intArr[i]);
		}
	}
}
