package chap14_exception;

public class _01_tryCatchFinally {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int[] arr = new int[3];
		
		int index = 0;
		
		while(true) {
			try {
				
			} catch(Exception e) {
				
			} finally {
				
			}
		}
	}

}
